### ISSUE TITLE
Which sentence embedding worked best in similarity task?

### ISSUE THREAD

**Issue by webstruck** [yogeshhk/FAQChatbot#1]
I see that you're using bunch of sentence vectorizers. In your experience, which one worked best for you. In my experience building a question answering system, OOTB BERT embeddings did not produce good results. But if you fine-tune BERT on STS datasets, then it performs much better for Semantic Similarity task. In general, USE still worked best for me.

**Comment by yogeshhk** [comment]
I have not bench-marked it extensively.
