### ISSUE TITLE
Dependencies / requirements

### ISSUE THREAD

**Issue by ablil** [yogeshhk/FAQChatbot#2]
The app need a lot of libraries as requirements, and there is no hint on the readme file o requirement/setup file.
It would be great if you add them.

I had the pip3 install the following libraries manullay:
* flask
* numpy
* scipy
* sklearn
* pandas
* nltk 
and much more

**Comment by snehilsanyal** [comment]
The requirements are given in the environment yaml file here: https://github.com/yogeshhk/FAQChatbot/blob/master/src/environment.yml 
You can check it out.

**Comment by yogeshhk** [comment]
Updated environment.yml to a smaller one

conda env create -f environment.yml
