### ISSUE TITLE
other language

### ISSUE THREAD

**Issue by zjtfo** [yogeshhk/FAQChatbot#3]
I would like to ask, if you want to change to Chinese FAQ, is it possible to replace the csv data? 
Thank you

**Comment by yogeshhk** [comment]
I have not tried but I think, with vectorizers like one-hot and tf-idf, it should not matter.

**Comment by zjtfo** [comment]
> I have not tried but I think, with vectorizers like one-hot and tf-idf, it should not matter.

Thank you very much.I did it.

**Comment by yogeshhk** [comment]
@zjtfo Hope its ok to close the issue
