### ISSUE TITLE
New GPT based embedings + Vector Db

### ISSUE THREAD

**Issue by yogeshhk** [yogeshhk/FAQChatbot#5]
Can someone implement LangChain + GPT-Index based FAQs in the same codebase?

**Comment by omknan60** [comment]
I am going to try to implement this.

**Comment by pritam1984314** [comment]
Greetings,

I have raised pull request OpenAI GPT based embedding support. I will work on vector db integration.
Please review pull request and share your suggestions/concerns.

Thanks and Regards,
Pritam

**Comment by yogeshhk** [comment]
Hi @pritam1984314 ,

Wonderful. Changes look fine to me, except at one place. I have added those comments at the PR page. Looks ok?

**Comment by yogeshhk** [comment]
@pritam1984314 I don't remember if the code submitted closes the issue. Closing it for now.
