### ISSUE TITLE
New added question/answer would not work

### ISSUE THREAD

**Issue by sichunqin** [yogeshhk/FAQChatbot#7]
I add the new question/answer to Greetings.cvs file as followed: 
Matrix,is great company,greetings

Then run chatbot. Open browser, and open the chatbot, and enter "Matrix" as question, but the reply is always "Hi". 
Not work as expected. 
Or I miss something that is required to make new added question work. Looking forward to reply! Thanks.

**Comment by yogeshhk** [comment]
Need to debug this. With 'tfidf' it may be easier @sichunqin

**Comment by sichunqin** [comment]
Thanks for the reply.  @yogeshhk 
I did use "tfidf" like below:
   faqslist = [os.path.join(base_path,"Greetings.csv")]
   faqmodel = FaqEngine(faqslist, 'tfidf')

And reduce the Greetings.cvs to minimum data as followed: 
Question,Answer,Class
Hello,Hi,greetings
Matrix,is great company,greetings
Tata,Bye,greetings

"Tata" can work well, but "Matrix" can not. 

I debug the code, and find the ind = 0 when ask "matrix", as the result, the answer is always the first one of question list. 
                ind = cos_sims.index(max(cos_sims))
                # print(ind)
                # print(questionset.index[ind])
                return self.data['Answer'][questionset.index[ind]]

I am wondering faqchatbot can only work well for limited set of sentences. I am new to the area, Maybe I am missing something.

**Comment by sichunqin** [comment]
I find the root course which that molde (question list) would saved into a file called tfidf.pkl. The saved file would be loaded into vectorizer automatically during initialization process. If need question is added, the pkl file needs to be regenerated in order to include new question. The pkl file can be simply deleted if need new question. 
The issue can be closed. Thanks.

**Comment by sichunqin** [comment]
Please see above solution.

**Comment by yogeshhk** [comment]
Thanks a lot for debugging and finding the root cause @sichunqin
